name: Docker CI Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      # STEP 1
      - name: Checkout Code
        uses: actions/checkout@v4

      # STEP 2
      - name: Build Docker Containers
        run: docker compose build